### DISCUSSION TITLE
pid_mode settings

### DISCUSSION THREAD

**Discussion by bigbread59** [ScratMan/HASmartThermostat#122] [Q&A] [answered]
**@ScratMan** 

I have the following question (just for my understanding):

why it is possible to define **kp, ki, kd** both by configuration in the .yaml file:

```
     kp:5
     ki:0.01
     kd: 500
```

either by calling the service:

```
service: smart_thermostat.set_pid_gain
date:
   kp:11.8
   ki:0.00878
targets:
   entity_id: climate.smart_thermostat_example
```

instead  we can define the
**pid_mode**
only by service
```
service: smart_thermostat.set_pid_mode
date:
   mode: 'off'
targets:
   entity_id: climate.smart_thermostat_example
```

**and NOT as a config in the .yaml file?**
