### DISCUSSION TITLE
[Feature request] Optional numerical output instead of ON/OFF

### DISCUSSION THREAD

**Discussion by tobimai** [ScratMan/HASmartThermostat#13] [Ideas]
I have Radiator valves which can be controlled by a 0-100 percentage, so it would be nice if the Thermostat could also output these values, as I want to control the TRV with an external Sensor. 
 
So a numerical output, basically just the value which is then converted to PWM, would be very useful in my setup.

I don't know how difficult this is, or if you are interested in this feature but I just wanted to suggest it as the problem came up for me.

**Comment by ScratMan** [comment]
Hi, you may use a template to get the **control_output** attribute in HA
`{{ state_attr('climate.salle_de_bain', 'control_output') | float }}`

This is the output of the PID.
You will still need a dummy switch or script for the heater entity.

**Reply by tobimai** [reply]
That works, thanks

**Reply by cmug81** [reply]
Can you give an example of how to use the template in real world? I have floor heating valves also controlled via 0..100% and I would like to control their state with Home Assistant

**Reply by cmug81** [reply]
> Can you give an example of how to use the template in real world? I have floor heating valves also controlled via 0..100% and I would like to control their state with Home Assistant

I think I understand. The idea is to create a new sensor, and then the value of that sensor comes from the state_attr.
Here is the sensor definition I created, which seems to work:
```
sensor:
  - platform: template
    sensors:
      valve_percent:
        friendly_name: "Heäting valve desired %-value"
        value_template: "{{ state_attr('climate.smart_thermostat_demo', 'control_output') | float }}"
```
