### DISCUSSION TITLE
Limiting the update rate of proportional valve changes?

### DISCUSSION THREAD

**Discussion by mairas** [ScratMan/HASmartThermostat#174] [Q&A] [answered]
Hi,

I just started playing with this great piece of software. I am trying to improve the control of those infamous Eurotronic Spirit TRVs (the Z-wave version in my case, unfortunately). I just got the initial setup done and will wait to see the results in the morning. There's already one thing I couldn't figure out, though: is it possible to limit the update rate when using proportional control? As it is, the valve control of the TRVs seems to be updated as often as the target_sensor sends an update. I'm worried it's a bit excessive and may drain the battery of the TRV too fast.

I've tried setting the keep_alive and sampling_rate but neither seems to have an impact.

Here's my current configuration:

```
climate:
  - platform: smart_thermostat
    name: Touhula N Smart Thermostat
    unique_id: touhula_n_smart_thermostat
    heater: number.touhula_n_radiator_thermostat_valve_control
    target_sensor: sensor.touhula_xiaomi_temperature
    min_temp: 10
    max_temp: 24
    ac_mode: False
    keep_alive:
      seconds: 240
    sampling_period:
      seconds: 300
    kp: 25
    ki: 0.0005
    kd: 750
    ke: 0.4
    pwm: 0
```

Thank you in advance!
