### DISCUSSION TITLE
How to change target temperature from external source

### DISCUSSION THREAD

**Discussion by newtask** [ScratMan/HASmartThermostat#179] [Q&A] [answered]
Is it possible to change attributes like target_temp from a service? 

I plan to use HASmartThermostat in combination with KNX and I want to control the target temperature via HA and via KNX buttons.

I have seen "async_set_preset_temp" but there is nothing for target_temp right?

**Comment by ScratMan** [comment, marked as answer]
Use climate.set_temperature

**Reply by newtask** [reply]
Thank you, so simple, so easy.


```
service: climate.set_temperature
data:
    temperature: 23
target:
  entity_id: climate.smart_thermostat_example
```
