### DISCUSSION TITLE
Optimizing Gas Boiler Operation: Syncing Multiple Heat Emitters with Smart Thermostat

### DISCUSSION THREAD

**Discussion by wiktor-z** [ScratMan/HASmartThermostat#184] [Q&A]
Thank you @ScratMan (and all other contributors!) for the time and effort put into developing this project. I've been using this smart thermostat for over one year to control the underfloor heating in my home by toggling the gas boiler relay, and it works great. This season, I expanded the control to include TRV heads on radiators. I purchased a set of TuYa TS0601/hy368 (_TZE200_cpmgn2cf) at a very attractive price. However, I'm facing difficulties configuring these TRVs to work with this smart thermostat.

In another repository's thread (https://github.com/jmcollin78/versatile_thermostat/discussions/202#discussion-5864303), I described my idea for optimizing the gas boiler's operation by synchronizing the activation of multiple heat emitters at once (in my case, underfloor heating and 5 TS0601 heads). The goal is to have them turn on simultaneously and turn off independently based on the temperature in each room.

Hence, I'm returning to this project with two fundamental questions:

1. If I create multiple climate devices (smart thermostat) with the same PWM parameter, will the calculation of the output and heating activation occur at the same time for all devices? I've taken measurements and determined suitable PID controller parameters for each room individually.

2. Has anyone configured the TS0601 to work with this smart thermostat? If so, how did you achieve it?

I appreciate any insights or experiences shared. Thank you!

**Comment by Machaeon** [comment]
> I've been using this smart thermostat for over one year to control the underfloor heating in my home by toggling the gas boiler relay, and it works great.

Can you please share your config? Right now I trying to setup smart thermostat for same system for first time.

**Reply by wiktor-z** [reply]
Sure thing! The part responsible for underfloor heating consists of two main physical components in the installation: the gas boiler and the underfloor heating pump. I have connected the Moes MS-104Z relay (model TS011F) to the gas boiler, and its state indicates whether the boiler should heat or not. The underfloor heating pump is powered by the TuYa smart plug (Model TS011F_plug_1).

On the Home Assistant side, I've created a smart thermostat as follows:
```
climate:
  - platform: smart_thermostat
    debug: true
    name: salon_ogrzewanie_pid_pwm #name of climate entity in HA
    heater: switch.plug_floor_heating #smart plug with floor pupm connected
    target_sensor: sensor.temp_salon_temperature #temperature sensor in my living room
    outdoor_sensor: sensor.sensor_front_temperature #external sensor to compensate loses when cold outside
    min_temp: 20
    max_temp: 25
    comfort_temp: 22
    target_temp: 22
    away_temp: 20
    ac_mode: False
    boost_temp: 25
    boost_pid_off: true
    preset_sync_mode: sync
    keep_alive:
      seconds: 60
    kp: 4.710468164
    ki: 0.00153936868
    kd: 1.177617041
    ke: 0.6
    pwm: 00:50:00
    cold_tolerance: 0.1
    hot_tolerance: 0.1
    precision: 0.1
    target_temp_step: 0.5
    min_cycle_duration: 00:05:00
    min_off_cycle_duration: 00:05:00
    sampling_period: 0
```
This climate entity can turn the underfloor heating pump on and off based on the calculated control and fill the PWM signal with the appropriate width based on the calculated the control_output. However, this isn't enough because, in this configuration, the pump would circulate cold water into the system. Therefore, two automations are needed in Home Assistant, one to inform the gas boiler to start heating and another to stop.

In simplified terms, these automations look like this:
```
trigger:
  - platform: state
    entity_id:
      - climate.living_room_heating_pid_pwm
    attribute: hvac_action
    to: heating
action:
  - type: turn_on
    entity_id: switch.switch_boiler
    domain: switch
mode: single
```
and the second one:
```
trigger:
  - platform: device
    type: turned_off
    entity_id: switch.switch_boiler
    domain: switch
condition:
  - condition: and
    conditions:
      - condition: device
        type: is_off
        entity_id: switch.switch_boiler
        domain: switch
action:
  - type: turn_off
    entity_id: switch.switch_boiler
    domain: switch
mode: single
```  
Which turns off the gas boiler when the pump has been turned off (and turns off automatically based on the operation of the climate entity).

These are just snippets from the automations. In my current setup, both underfloor heating and TRV heads can trigger the boiler. The condition in the second automation contains many more conditions for checking (the boiler can turn off when ALL rooms have reached their target temperatures).

To complete the setup, you'll need a thermostat card in the Lovelace UI. Currently, I'm using the Simple Thermostat card.
Important note: I keep the card in 'heating' mode at all times, and the underlying climate device decides when heat is needed and when to go into an idle state.
<img width="387" alt="image" src="https://github.com/ScratMan/HASmartThermostat/assets/13226866/0912c9ee-9daa-4fbc-8c1a-abf01bf59153">

Disclaimer: Be sure to adjust the PID parameters to your installation; the ones provided work in my case.
and this is how it works in practice for me:
<img width="1286" alt="image" src="https://github.com/ScratMan/HASmartThermostat/assets/13226866/c544f982-329b-4475-9f6e-bd795d7dc232">
