### DISCUSSION TITLE
Autotune feature usage.

### DISCUSSION THREAD

**Discussion by bigbread59** [ScratMan/HASmartThermostat#21] [Q&A] [answered]
Hi all,

I am trying to use HASmartThermostat, unfortunately with unsatisfactory results so far.

I can't find the right kp, ki and kd parameters manually.

I have made a few attempts, sometimes the temperature does not reach the set point, other times it goes far beyond (diverges).

I have tried to use the auto_tuning function but I have the following problems.

**1)**
After setting up the following configuration

climate:
  - platform: smart_thermostat
    #entity_id: smart_thermostat_PP
    name: PID_Thermostat
    heater: switch.contact_clean_thermostat
    target_sensor: sensor.xiaomi_wsdcgq11lm_002_temperature
    precision: 0.1
    min_temp: 15
    max_temp: 21
    ac_mode: False
    target_temp: 17
    keep_alive:
      seconds: 60
    away_temp: 14
    kp: 1
    ki: 5
    kd: 20
    pwm: 00:15:00
    sampling_period: 00:10:00
    autotune: "pessen-integral"

I restart HA, (the ambient temperature is about 19 ° C)
I set the temperature setpoint at 21 ° C

At this point (it seems) nothing happens: the heater control switch remains off so the heating does not start.
Am I wrong something?

**2)**
I'm not very familiar with HA, how do I check the autotune_status attribute for success ?

Many thanks

**Comment by ScratMan** [comment]
Hello, in the latest 2021.11.8-beta4, the autotune doesn't need a step, it will directly use the set point that is set a few temperature samples after the reboot. You may use a set point aligned with your ambient temperature at time of restarting HA, for example, if your thermostat is set to 18°C but the ambient temperature is 19.7°C before restarting, you could set 19°C, then restart and let the autotuner start with this 19°C as target. It will start with a step-down, so waiting for the temperature to drop below set-point minus the noise band before switching on the heater.

I would recommend you to set the `noiseband` setting according to your sensor's measurements rate and accuracy :
* if the sampling rate of the sensor is fast (few seconds) and temperature moves quickly up and down (fast heating system and/or low insulation in the room), the `noiseband` should be higher (keep 0.5)
* if the sampling rate of the sensor is low (refreshing temperature after several minutes) or temperature moves slowly (high inertia, like floor heating, with good insulation), you should set a lower `noiseband` (for example 0.2), otherwise the temperature oscillation period will be very long.

The `lookback` parameter is important too, I used `lookback` set between 6 and 10 hours while simulating autotuning with some data exported by a user of the thermostst, and it worked well for the autotuner, the temperature oscillation period was around 2 hours on his heating system, and the gains computed by the autotuner were quite good after the first testing he did.

You can check the status of the autotuner by using the "Development tools" in HA, in the "States" section. You can select your climate entity and its state and attributes will be shown, you will see the `autotune_status` attribute here and new Kp, Ki and Kd if the autotune succeeded (it will also be shown in the log, with different gains computed with all the tuning rules).
Or you can add sensor templates in your configuration file to directly create some sensors monitoring the attributes you want, like this example that monitors the PID outputs : 
```
sensor:
  - platform: template
    sensors:
      smart_thermostat_output:
        friendly_name: PID Output
        unit_of_measurement: "%"
        value_template: "{{ state_attr('climate.your_entity_id', 'control_output') | float }}"
      smart_thermostat_p:
        friendly_name: PID P
        unit_of_measurement: "%"
        value_template: "{{ state_attr('climate.your_entity_id', 'pid_p') | float }}"
      smart_thermostat_i:
        friendly_name: PID I
        unit_of_measurement: "%"
        value_template: "{{ state_attr('climate.your_entity_id', 'pid_i') | float }}"
      smart_thermostat_d:
        friendly_name: PID D
        unit_of_measurement: "%"
        value_template: "{{ state_attr('climate.your_entity_id', 'pid_d') | float }}"
```

Don't hesitate to share you results
