### DISCUSSION TITLE
Using KNX switch as heater, "[homeassistant.helpers.service] Referenced entities switch.heater are missing or not currently available"

### DISCUSSION THREAD

**Discussion by cmug81** [ScratMan/HASmartThermostat#227] [Q&A] [answered]
Just configured a KNX switch, which triggers my KNX valve actuator for opening a floor heating valve. However, when I configure the smart thermostat to try and increase temperature, my HA log gets filled with the error that the entity is not available. The switch works fine via HA UI.

What am I doing wrong?

Here is the configuration

```
- platform: smart_thermostat
  name: Makuuhuone 1
  unique_id: smart_thermostat_makuuhuone1
  heater: switch.heater
  target_sensor: sensor.mh1_lampotila
  outdoor_sensor: sensor.hario_outdoor_temperature
  min_temp: 19
  max_temp: 25
  ac_mode: False
  target_temp: 22
  keep_alive:
    seconds: 60
  away_temp: 19
  kp: 5
  ki: 0.01
  kd: 500
  pwm: 0
```

The KNX device is a ABB VAA/S 6.230.2.1, https://new.abb.com/products/2CDG110116R0011/vaa-s-6-230-2-1
