### DISCUSSION TITLE
PID Thermostat over a Climate?

### DISCUSSION THREAD

**Discussion by MBRetrofit** [ScratMan/HASmartThermostat#281] [General]
Is it possible? To use a Climate entity as a heater - to override the Climate settings and to apply PID only to modulation of the flame? The modulation algo in mostly gas boilers is quite the same as the PID algo, - difference between request and current temp over the exterior temp...-.

**Comment by ScratMan** [comment]
Hi, yes, it's possible, but you need an intermediate switch helper entity, for example `input_boolean.chauffage_chambre_3` and an automation that will trigger on this entity's state changes and drive the climate entity to set either high or low setpoint to start and stop the boiler.

Example, I'm using this to control some Netatmo climates in bedrooms.
PID thermostats declared like this:

```yaml
- platform: smart_thermostat
  name: Chambre parentale
  unique_id: chambre_parentale
  heater: input_boolean.chauffage_chambre_3
  target_sensor: sensor.popp_mold_chambre_3
  outdoor_sensor: sensor.fgbs222_smart_module_1_garage_temperature_2
  min_temp: 7
  max_temp: 30
  ac_mode: False
  target_temp: 19
  away_temp: 14
  sleep_temp: 18
  eco_temp: 19
  comfort_temp: 20
  boost_temp: 25
  keep_alive: 00:01:00
  min_cycle_duration: 00:05:00
  precision: 0.1
  kp: 100
  ki: 0.007
  kd: 125000
  ke: 0
  pwm : 900

```

And the automation to manage the link between virtual and physical thermostats:

```yaml
alias: Chauffage chambres
description: ""
triggers:
  - entity_id:
      - input_boolean.chauffage_chambre_1
      - input_boolean.chauffage_chambre_2
      - input_boolean.chauffage_chambre_3
    trigger: state
  - minutes: /30
    trigger: time_pattern
actions:
  - if:
      - condition: state
        entity_id: input_boolean.chauffage_chambre_1
        state: "on"
    then:
      - data:
          temperature: 25
        target:
          entity_id: climate.netatmo_chambre_1
        action: climate.set_temperature
    else:
      - data:
          temperature: 14
        target:
          entity_id: climate.netatmo_chambre_1
        action: climate.set_temperature
  - if:
      - condition: state
        entity_id: input_boolean.chauffage_chambre_2
        state: "on"
    then:
      - data:
          temperature: 25
        target:
          entity_id: climate.netatmo_chambre_2
        action: climate.set_temperature
    else:
      - data:
          temperature: 14
        target:
          entity_id: climate.netatmo_chambre_2
        action: climate.set_temperature
  - if:
      - condition: state
        entity_id: input_boolean.chauffage_chambre_3
        state: "on"
    then:
      - data:
          temperature: 25
        target:
          entity_id: climate.netatmo_chambre_3
        action: climate.set_temperature
    else:
      - data:
          temperature: 14
        target:
          entity_id: climate.netatmo_chambre_3
        action: climate.set_temperature
mode: parallel
max: 10

```
