### DISCUSSION TITLE
Bit confused as to how i link this to a specific TRV - new to HA / YAML may be why.

### DISCUSSION THREAD

**Discussion by ScottishB** [ScratMan/HASmartThermostat#289] [General]
Hey All,
  Im trying to get this to work with a specific thermostat at the moment as a test. 

Firstly i installed Smart Thermostat PID via HACS, no issue there.

Then i installed the following code via climate.yaml (linked to via configuration.yaml with climate: !include climate.yaml)

```
- platform: smart_thermostat
  name: Smart Thermostat Single ON/OFF Heater Example
  unique_id: smart_thermostat_single_on_off_heat_example
  heater: number.my_office_thermostat_valve_opening_degree
  target_sensor: sensor.my_office_temperature
  min_temp: 7
  max_temp: 28
  ac_mode: False
  target_temp: 19
  keep_alive:
    seconds: 60
  away_temp: 14
  kp: 50
  ki: 0.01
  kd: 2000
  pwm: 0
```

The TRC is a SONOS TRVZB in case thats relevant.

With the code above, i see my TRV in the dashboard as, "Smart Thermostat Single ON/OFF Heater Example" as expected, it also picks up the current temperature of the sensor in the thermostat, i assume from target_sensor:.

Moving the controls pas the current sensor temp changes the thermostat to heating but checking number.my_office_thermostat_valve_opening_degree the value does not seem to be changing.

Looking into developer tools - states - number.my_office_thermostat_valve_opening_degree it stays at 100 and i can also see that same value set in Zigbee2MQTT on the thermostat itself.

So im not sure what i am doing wrong here, should Smart Thermostat PID be controlling that value and opening the valve for that thermostat or have i funimentally just misunderstood something?

My understanding is that by adjusting the target temperature in the dial, the valve_opening_degree value will change (its default at 100 - fully closed - should it drop gradually down to 1?) - is that correct?

**Comment by ovizii** [comment]
Just curios, is your SONOS TRVZB a proper TRV which presents a climate entity to HA? 
I'm asking because this integration here seems to only be able to control heating via a switch. So it seems the wrong tool for you.

Glad to be proven wrong, as I landed here to try to connect with my Tuya	TS0601_thermostat which only has a climate entity but no switch.

**Comment by ScottishB** [comment]
Hi, yes it is and I think you are correct as I want able to get this working and gave up.

**Comment by ScratMan** [comment]
Hi, if your valve is controlled as a thermostat in HA, you can create an input_boolean helper and use it for the heater entity in the smart thermostat, then use an automation to force the setpoint of the TRV either very high or very low to force it on or off, like this:

```yaml
alias: Chauffage chambres
description: ""
triggers:
  - entity_id:
      - input_boolean.chauffage_chambre_parentale
      - input_boolean.chauffage_chambre_apolline
      - input_boolean.chauffage_chambre_adonis
    trigger: state
  - minutes: /30
    trigger: time_pattern
conditions:
    - condition: state
      entity_id: climate.netatmo_couloir
      attribute: preset_mode
      state: schedule
actions:
  - if:
      - condition: state
        entity_id: input_boolean.chauffage_chambre_adonis
        state: "on"
    then:
      - data:
          temperature: 25
        target:
          entity_id: climate.netatmo_chambre_adonis
        action: climate.set_temperature
    else:
      - data:
          temperature: 14
        target:
          entity_id: climate.netatmo_chambre_adonis
        action: climate.set_temperature
  - if:
      - condition: state
        entity_id: input_boolean.chauffage_chambre_apolline
        state: "on"
    then:
      - data:
          temperature: 25
        target:
          entity_id: climate.netatmo_chambre_d_apolline
        action: climate.set_temperature
    else:
      - data:
          temperature: 14
        target:
          entity_id: climate.netatmo_chambre_d_apolline
        action: climate.set_temperature
  - if:
      - condition: state
        entity_id: input_boolean.chauffage_chambre_parentale
        state: "on"
    then:
      - data:
          temperature: 25
        target:
          entity_id: climate.netatmo_chambre_parentale
        action: climate.set_temperature
    else:
      - data:
          temperature: 14
        target:
          entity_id: climate.netatmo_chambre_parentale
        action: climate.set_temperature
mode: parallel
max: 10
```


But I strongly recommend you to add a small temperature sensor to be used by the smart thermostat, and place it far from the radiator so the smart thermostat can monitor the real ambient temperature. Valves being on the radiators, their sensor can't monitor ambient temperature correctly.

**Reply by ovizii** [reply]
Very good idea, thanks! I will give it a try. MY thermostat, has OFF/Auto/Heat settings and HEAT means continuously heat, so I will use that and OFF to create an ON/OFF scenario.

**Reply by ScratMan** [reply]
If your valve directly has an on off mode, it's even simpler, you can code a template switch using YAML that can call the service to control, then you don't even need an automation.

```yaml
# Example configuration.yaml entry
switch:
  - platform: template
    switches:
      bedroom_heater:
        turn_on:
          action: climate.turn_on
          target:
            entity_id: climate.your_trv_valve
        turn_off:
          action: climate.turn_off
          target:
            entity_id: climate.your_trv_valve
```

More details:
https://www.home-assistant.io/integrations/switch.template/

Personally I used an automation because my Netatmo valves need a regular refresh otherwise it returns to it standard behaviour ignoring my smart thermostat control.
