### DISCUSSION TITLE
Please help me get started

### DISCUSSION THREAD

**Discussion by ovizii** [ScratMan/HASmartThermostat#297] [Q&A] [answered]
So here I am, starting from scratch. Will this create a basic climate entity (my configuration file contains: climate: !include climate.yaml) so it is being loaded.

```
  - platform: smart_thermostat
    name: Lounge Heating
    unique_id: lounge_heating
    heater: input_boolean.heating_lounge
    target_sensor: sensor.loungetemphum_temperature
    precision: 0.1
    target_temp_step: 0.5
    min_temp: 8
    max_temp: 26
    ac_mode: False
    target_temp: 12
    keep_alive:
      seconds: 60
    away_temp: 12
    kp: 100
    ki: 0
    kd: 0
    ke: 0
    pwm: 0
    min_cycle_duration: 00:05:00
    min_off_cycle_duration: 00:05:00
```

The result is a climate entity, which currently measures say 20 C and I have set the target temp to 22 C in the hopes that this would flip the input boolean to ON and yet it doesn't.

Isn't that how this is supposed to work?

I have further automations down the line, i.e. what should happen when that input booleans gets set to ON or OFF but shouldn't this code above trigger the boolean when the measured temp goes above or below the target temp?

Please help, it seems I am failing at the very beginning :-)
