### DISCUSSION TITLE
[Feature Request] Add windows Management

### DISCUSSION THREAD

**Discussion by Djal94** [ScratMan/HASmartThermostat#9] [Ideas]
Thanks for the work. Please could you add management for windows please. (Turn off when windows is open).

Thanks

**Comment by nagyrobi** [comment]
That can be easily done using automations in Home Assistant...

**Comment by Djal94** [comment]
of course

**Comment by nagyrobi** [comment]
```
group: 
  doors_and_windows:
    name: Any door or window
    entities:
      - binary_sensor.window1
      - binary_sensor.door1
      - ....
```

```
- id: heating_on_outside_temp
  trigger:
  - platform: state
    entity_id: 'group.doors_and_windows'
    to: 'off' #windows closed
  action:
  - service: climate.turn_on
    data:
      entity_id: climate.heater

- id: heating_off_outside_temp
  trigger:
  - platform: state
    entity_id: 'group.doors_and_windows'
    to: 'on' # windows open
  action:
  - service: climate.turn_off
    data:
      entity_id: climate.heater
```
