### DISCUSSION TITLE
Controlling a Z-Wave Radiator Thermostat with Valve Control and external Temperature Sensor (1-wire)

### DISCUSSION THREAD

**Discussion by simonmarwitz** [ScratMan/HASmartThermostat#96] [Show and tell]
First of all, thanks @ScratMan for the great work on HASmartThermostat 👏

My hot-water radiators are equipped with Z-Wave Thermostats that allow to direct control of the valve position (Eurotronic Comet Z-Wave). Their built-in thermostat controller works poorly; of course it only knows the temperature close to the radiator. But I have 1-wire temperature sensors in every room, to measure the real room temperature. 

I came up with the following configuration, to use the Smart Thermostat for controlling the valves and I am very happy with the results.  It took quite a while for me to have it working the way I want. Sharing my configuration here, for anyone that might be interested in doing something similar.

configuration.yaml
```yaml
# create a dummy switch, to connect the to the Smart Thermostat, as we will not be using PWM
switch:
  - platform: template
    switches:
      smart_thermostat_dummy_switch:
        unique_id: ZZZZZZZZZ
        turn_on:
          - delay: 0
        turn_off:
          - delay: 0

# the one wire sensor reports temperature on every temperature change of 0.1 °C
# the z-wave thermostat wakes up regularly every 240 seconds and can not accept changes to the valve in between
# the derivative parts of the smart thermostat thus become useless
# create a template sensor, that syncs the temperature reports to smart_thermostat  with the wake up times of the z-wave device
template:
  - trigger:
      - platform: device
        device_id:  XYXYXYX
        domain: zwave_js
        type: state.node_status
        entity_id: sensor.bedroom_node_status
        from: asleep
        to: awake
    sensor:
      - name: "Bedroom Temperature (Sync)"
        state: '{{states("sensor.XZXZXZX_temperature")}}'
        device_class: 'temperature'
        unit_of_measurement: "°C"
        unique_id: XXXXXXXXXX

# set up smart thermostat with pwm: 0 for direct use of control_output to drive the valve
climate:
 - platform: smart_thermostat
   name: Smart Thermostat Bedroom
   unique_id: smart_thermostat_bedroom
   heater: switch.smart_thermostat_dummy_switch
   target_sensor: sensor.bedroom_temperature_sync
   outdoor_sensor: sensor.ZXYXZXY_temperature
   min_temp: 7
   max_temp: 28
   ac_mode: False
   keep_alive:
     seconds: 240
   kp : 25
   ki : 0.0005
   kd : 750
   ke: 0.4
   pwm : 0
```

automations.yaml
```yaml
alias: SmartThermostatValveControlBedroom
description: ""
trigger:
  - platform: device
    device_id: XYXYXYX
    domain: zwave_js
    type: state.node_status
    entity_id: sensor.bedroom_node_status
    from: asleep
    to: awake
condition:
  - condition: state
    entity_id: climate.smart_thermostat_bedroom
    state: heat
  - condition: template
# check, if the control_output has actually changed to reduce commands sent to the z-wave device
    value_template: >-
      {{states('number.bedroom_valve_control')|round !=
      (state_attr('climate.smart_thermostat_bedroom','control_output')/100*99)|round}}
action:
  - service: number.set_value
    data_template:
# conversion of control_output (float in range 0 .. 100) to valve control (integers in range 0 .. 99)
      value: >-
        {{
        (state_attr('climate.smart_thermostat_bedroom','control_output')/100*99)|round}}
    target:
      entity_id: number.bedroom_valve_control
initial_state: true
trace:
  stored_traces: 20
mode: restart

alias: AutoSwitchThermostatModeBedroom
description: ""
trigger:
  - platform: state
    entity_id:
      - climate.smart_thermostat_bedroom
    to: heat
  - platform: state
    entity_id:
      - climate.smart_thermostat_bedroom
    to: "off"
condition: []
action:
  - if:
      - condition: state
        entity_id: climate.smart_thermostat_bedroom
        state: heat
    then:
      - if:
          - condition: device
            device_id: XYXYXYX
            domain: climate
            entity_id: climate.bedroom
            type: is_preset_mode
            preset_mode: Manufacturer specific
        then: []
        else:
          - service: climate.set_preset_mode
            data:
              preset_mode: Manufacturer specific
            target:
              device_id: XYXYXYX
    else:
      - if:
          - condition: device
            device_id: XYXYXYX
            domain: climate
            entity_id: climate.bedroom
            type: is_preset_mode
            preset_mode: Manufacturer specific
        then:
          - service: number.set_value
            data:
              value: "0"
            target:
              entity_id: number.bedroom_valve_control
          - service: climate.turn_off
            data: {}
            target:
              device_id: XYXYXYX
mode: single

```
Here you can see it in action

The target, vs. current temperature (Deviations in the morning hours are due to setting hvac_mode: 'off', which is not reflected in the target temperature):
![image](https://user-images.githubusercontent.com/25247720/207267053-dae54459-bdb5-4857-9cea-687f75eb9f9d.png)
The valve control of the radiator:
![image](https://user-images.githubusercontent.com/25247720/207267111-09bbe8e1-735a-4cd9-ad4c-438340381c63.png)

(I also created an open-window detection automation based on the room temperature measurements, that turns off thermostat control. If anyone is interested, I can also share it here.)
