### ISSUE TITLE
Add an HVAC function to specifie witch mode to turn on the termostat

### ISSUE THREAD

**Issue by fasavard** [ScratMan/HASmartThermostat#103]
I currently have a setup with multiple insteon thermostat. Witch all have many hvac function ( Heat, cool, fan)

Currently, the tool support a on/off toggle switch to support the pid control. It would be great to have an option to specify the signal send to turn on the thermostat. 
Something like:
`configuration.yaml
climate:
  - platform: smart_thermostat
    name: Smart Thermostat Example
    unique_id: smart_thermostat_example
    heater: switch.on_off_heater
    target_sensor: sensor.ambient_temperature
    min_temp: 7
    max_temp: 28
    ac_mode: False
    hvac_mode: (" Here we choose between ON, HEAT, COOL or whatever our thermostat signal is compatible with)
    target_temp: 19
    keep_alive:
      seconds: 60
    away_temp: 14
    kp: 5
    ki: 0.01
    kd: 500
    pwm: 00:15:00
`

**Comment by fasavard** [comment]
So i found (probably the solution that others are doing) to fix this. 
For other people having this issue, using the template system can be use to convert you entitie heat into a switch. 

For this, you can go in your configuration.yaml file, and add something like this:

```
switch:
  - platform: template
    switches:
      heated_floor_living_room:
        turn_on:
          service: climate.set_hvac_mode
          data:
            hvac_mode: "heat"
          target:
            entity_id: climate.34_d2_34_main
        turn_off:
          service: climate.set_hvac_mode
          data:
            hvac_mode: "cool"
          target:
            entity_id: climate.34_d2_34_main
```

Setup is not entirely working but the switch part of the termostat is good.
