### ISSUE TITLE
UI preset value is out of synch with preset request

### ISSUE THREAD

**Issue by dominig** [ScratMan/HASmartThermostat#131]
**Describe the bug**
I try to change the preset by a simple script and expect to see new values reflected in the UI

**To Reproduce**
1. Run manually my simple following test automation
```
alias: Force reset Temp default
description: ""
trigger: []
condition: []
action:
  - service: smart_thermostat.set_preset_temp
    data:
      away_temp: 5
      comfort_temp: 19
      eco_temp: 16
    target:
      area_id: chambre
mode: single
```

**Expected behavior**
The UI should have been updated with the new value at least after a UI webpage forced reload or at least after an HA restart.
It does not aven mirror my configuration.yalm
```
climate:
  - platform: smart_thermostat
    name: Smart Thermostat Bedroom
    unique_id: smart_thermostat_bedroom
    heater: light.tz3000_u3oupgdy_ts0004_light_2
    target_sensor: sensor.temperature_bedroom_temperature_2
    outdoor_sensor: sensor.temperature_balcony_temperature
    min_temp: 7
    max_temp: 25
    ac_mode: False
    target_temp: 19
    away_temp: 5
    eco_temp: 16
    comfort_temp: 19
    keep_alive: 00:05:00
    away_temp: 14
    kp: 5
    ki: 0.01
    kd: 500
    pwm: 00:05:00
    min_cycle_duration: 00:01:00
```
**Screenshots**
UI does not change.
![image](https://user-images.githubusercontent.com/1193120/219952436-3c211106-38cd-4231-982a-b9a13fcb4d99.png)
Furthermore, as the UI is not showing the expected values, I have idea of what are the real value used as a target.

**Desktop (please complete the following information):**
 - OS: Linux OpenSUSE 15.3
 - Browser  Firefox 
 - Version 102.6.0esr (64 bits)

**Comment by ScratMan** [comment]
Hello, not sure to understand what you want to do, but the `set_preset_temp` service doesn't activate a preset, it only allows changing the values of the presets during runtime.
If you want to activate a preset, you should use the `climate.set_preset_mode` service, example below:
```
service: climate.set_preset_mode
data:
  preset_mode: away
target:
  entity_id: climate.salle_de_bain
```

**Comment by dominig** [comment]
Hello,
I just try to force new value on the default by script and I would then expect the UI to display the new value.
The script to set the value uses 
`  smart_thermostat.set_preset_temp`
While the script the activate the preset uses:
```
  action:
  - service: climate.set_preset_mode
    data:
      preset_mode: away
    target:
      area_id: chambre
```
I do not know if any of the actions works as the UI does only reflect the select preset but not the target temperature.
As seen in initial screen capture.

**Comment by ScratMan** [comment]
If I understand well:

- your thermostat is set to the comfort preset with 20°C
- a script changes the comfort preset temperature to 19°C using set_preset_temp service
- the UI remains on the comfort preset and the target temperature remains 20°C, while you'd like it to either switch to "none" preset or switch to the new comfort temperature
Right ?
Then your script should apply the preset after changing its temperature.

**Comment by dominig** [comment]
What I want to do is to force the preset value (e.g. confort 20C)
then to activate a given preset (eg confort)
I hope that the target value will become 20C and that the UI will show the 20C and confort.
In fact I want to do by script what can be done via the UI where when a preset is selected the preset name and target value is displayed.
I do not understand why by script I do only see the preset mode displayed while the target temperature remains the same. SO I do not know what the system does.

**Comment by ScratMan** [comment]
So your script must call both services set_preset_temp and then set_preset_mode, like this :

```yaml
alias: Set Preset
sequence:
  - service: smart_thermostat.set_preset_temp
    data:
      eco_temp: 19
    target:
      entity_id: climate.salle_de_bain
  - service: climate.set_preset_mode
    data: {}
    target:
      entity_id: climate.salle_de_bain
mode: single

```
