### ISSUE TITLE
Simplifying integration of Open Windows detection

### ISSUE THREAD

**Issue by dominig** [ScratMan/HASmartThermostat#132]
**Describe the bug**
No where any easy information is provided to integrate an open window detection.

**To Reproduce**
1. Check all documentation , nothing anywhere
**Expected behaviour**
Open window detection is an expected feature of a good heating integration.
I rely on simple open window detection, as solution based on temperature drop are unreliable and slow.

I would have expected to find a description on how to setup my system to Away and how to resume it to previous are at least know status.

**Screenshots**
I finally, after reading some python code, in particular, the import statements,  have found a method using the base climate services. Unfortunately I am not sure that is works as UI feedback is misbehaving (see issue #131)

Would be nice to get lines in the Readme.md about the best model to benefit of the Generic Thermostat in HASsmartThermostat in the context of that use case  :-)
```
alias: Window Bedroom Opened Stop heating
description: Set the heating to Away mode when window is opened
trigger:
  - type: opened
    platform: device
    device_id: a856b646ae1ff52860c226fe9ca67583
    entity_id: binary_sensor.kitchen_window1_iaszone
    domain: binary_sensor
    for:
      hours: 0
      minutes: 1
      seconds: 0
condition: []
action:
  - service: climate.set_preset_mode
    data:
      preset_mode: away
    target:
      area_id: chambre
mode: single


alias: Window Bedroom Closed Activate heating
description: Set the heating to Confort mode when window is closed
trigger:
  - type: not_opened
    platform: device
    device_id: a856b646ae1ff52860c226fe9ca67583
    entity_id: binary_sensor.kitchen_window1_iaszone
    domain: binary_sensor
    for:
      hours: 0
      minutes: 10
      seconds: 0
condition: []
action:
  - service: climate.set_preset_mode
    data:
      preset_mode: confort
    target:
      area_id: chambre
mode: single

```

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
