### ISSUE TITLE
How to set heater control output to be an integer and how to set a max value (ex: 99 and not 100)

### ISSUE THREAD

**Issue by leelouch** [ScratMan/HASmartThermostat#222]
**Is your feature request related to a problem? Please describe.**
Hi I have a valve that support values between 0 to 99% , 100 is not supported and also it have to be an int value.

**Describe the solution you'd like**
I would like that heater position to be an integer only and not a float and a max of 99. 
is there a way to configure that ? 

**Describe alternatives you've considered**
go through another number to intercept smart thermostat value and do a x .99 and round them ! 

any existing solution  ? 
thanks for help.

```
my code : 
- platform: smart_thermostat
  name: Smart Thermostat test
  unique_id: smart_thermostat_test
  heater: input_number.position_thermostat_living_room
  target_sensor: input_number.temperature_test
  min_temp: 7
  max_temp: 28
  ac_mode: False
  target_temp: 19
  keep_alive:
    seconds: 60
  away_temp: 14
  kp: 50
  ki: 0.004167
  kd: 0
  pwm: 0
  sampling_period: 00:10:00
```
