### ISSUE TITLE
heater: Referenced entities are missing or not currently available

### ISSUE THREAD

**Issue by chungalunga** [ScratMan/HASmartThermostat#225]
**Describe the bug**
Whatever I input in the "heater" section is reported as "missing or not currently available", as a result the thermostat is always in "idle" mode. Temperature sensor is picked up fine and works as expected.

**To Reproduce**
Enter any entity in the "heater" section.

**Expected behavior**
It should work?:)

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser chrome
 - Version 126
 - HA Core 2024.7.0
 - HAOS 12.4

**Additional context**
I tried with input_boolean as well as a switch with the same result. I can access these entites without problems via automations / script.

**Comment by ScratMan** [comment]
Hello, could you please provide Smart Thermostat integration version and configuration file ?

**Comment by chungalunga** [comment]
Hello, thanks for such a quick help!

Smart Thermostat integration version: 2024.6.1

Configuration file:

```
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

climate:
  - platform: smart_thermostat
    name: Termostat living room
    unique_id: termostat_living_room
    heater: input_boolean.on_off_heater
    target_sensor: sensor.temp_senzor_temperature
    min_temp: 7
    max_temp: 28
    initial_hvac_mode: "heat"
    ac_mode: False
    target_temp: 19
    keep_alive:
      seconds: 60
    away_temp: 14
    kp: 5
    ki: 0.01
    kd: 500
    pwm: 0

```
I ommited http section from the config, I suppose it should be irrelevant.

Helper:
![helper](https://github.com/ScratMan/HASmartThermostat/assets/11133890/8ff1b655-33c4-4c2c-ac68-970746eaf85e)
