### ISSUE TITLE
Set Preset Mode no longer supported?

### ISSUE THREAD

**Issue by mutasim** [ScratMan/HASmartThermostat#237]
As per [this comment](https://github.com/ScratMan/HASmartThermostat/issues/131#issuecomment-1436002652) setting preset mode seemed to be an option.

I've created a smart thermostat but I'm not able to set preset mode.

The following error:

`Failed to perform the action climate.set_preset_mode. Entity climate.openplan_smart_thermostat does not support this service.`

**Comment by ScratMan** [comment]
Hi, just tested, it works.

```yaml
action: climate.set_preset_mode
target:
  entity_id: climate.salle_de_bain
data:
  preset_mode: boost

```

Please ensure the selected preset is enabled (use the `smart_thermostat.set_preset_temp` action to enable/set/disable the presets temperatures).
