### ISSUE TITLE
Switch turning ON despite temperature way over target 

### ISSUE THREAD

**Issue by wmoc** [ScratMan/HASmartThermostat#250]
**Describe the bug**
Current temperature is correctly read to be 19C. Target temperature is set to 5C. I think in this case the smart_thermostat should not turn on the heater. Is there something that I'm missing? The configuration uses default values from readme.md. 

**Screenshots**
<img width="1271" alt="Screenshot 2024-10-21 at 16 40 20" src="https://github.com/user-attachments/assets/f6fadba4-31bd-4641-a71f-77793932fc27">

**Additional context**

Entity config:
```
  - platform: smart_thermostat
    name: Bathroom heater PID
    unique_id: bathroom_heater_pid
    heater: input_boolean.bathroom_heater_switch
    target_sensor: sensor.bathroom_heater_temperature
    min_temp: 1
    max_temp: 28
    ac_mode: False
    target_temp: 19 # in my understanding this doesn't matter as it is only the initial setting 
    keep_alive:
      seconds: 60
    kp: 50
    ki: 0.01
    kd: 2000
    pwm: 00:15:00
```
