### ISSUE TITLE
Heating not immediately starting - "Cycle is too short"

### ISSUE THREAD

**Issue by somerandoname** [ScratMan/HASmartThermostat#251]
When switching the thermostat from 'off' to 'heat' the switch isn't immediately being turned on despite a high enough PID output.    

According to the log the cycle time is too short, but with an output of 70.9 it should be well above the 'min_cycle_duration' of 6 min. What am I misunderstanding?

Log message:
```
2024-10-24 18:21:04.880 DEBUG (MainThread) [custom_components.smart_thermostat.climate] climate.smart_thermostat: New PID control output: 70.9 (error = 1.56, dt = 0.00, p=19.40, i=51.50, d=-0.00, e=0.00)
2024-10-24 18:21:04.880 INFO (MainThread) [custom_components.smart_thermostat.climate] climate.smart_thermostat: OFF time passed. Request turning ON switch.daikin_toggle_heating
2024-10-24 18:21:04.880 INFO (MainThread) [custom_components.smart_thermostat.climate] climate.smart_thermostat: Reject request turning ON switch.daikin_toggle_heating: Cycle is too short
```

<details>
<summary> Smart Thermostat config </summary>

```
- platform: smart_thermostat
  name: Smart Thermostat
  unique_id: smart_thermostat
  heater: switch.daikin_toggle_heating
  cooler: switch.daikin_toggle_cooling
  target_sensor: sensor.thermal_comfort_humidex
  min_temp: 12
  max_temp: 28
  ac_mode: true
  keep_alive:
    seconds: 60
  sampling_period: 0
  kp: 12.483
  ki: 0.04
  kd: 979.349
  pwm: 00:15:00
  min_cycle_duration: 00:06:00
  min_off_cycle_duration: 00:01:00
  target_temp_step: 0.1
  target_temp: 16
  eco_temp: 16
  comfort_temp: 20
  boost_temp: 21
  preset_sync_mode: sync
  sensor_stall: 0
  debug: true
```

</details>

<details>
<summary> Switch config </summary>

```
- platform: template
  switches:
    daikin_toggle_heating:
      friendly_name: "Daikin toggle heating"
      unique_id: daikin_toggle_heating
      value_template: >
        {% set state = states('climate.daikin') %}
        {% set temp = state_attr('climate.daikin, 'temperature') %}
        {{ state == 'heat' and temp == 30 }}
      turn_on:
        action: script.turn_on
        target:
          entity_id: script.daikin_on
      turn_off:
        action: script.turn_on
        target:
          entity_id: script.daikin_off

- platform: template
  switches:
    daikin_toggle_cooling:
      friendly_name: "Daikin toggle cooling"
      unique_id: daikin_toggle_cooling
      value_template: >
        {% set state = states('climate.daikin') %}
        {% set temp = state_attr('climate.daikin', 'temperature') %}
        {{ state == 'cool' and temp == 18 }}
      turn_on:
        action: script.turn_on
        target:
          entity_id: script.daikin_on
      turn_off:
        action: script.turn_on
        target:
          entity_id: script.daikin_off
```

</details>
