### ISSUE TITLE
PID MODE NOT  "AUTO" BY DEFAULT

### ISSUE THREAD

**Issue by 96Ems** [ScratMan/HASmartThermostat#252]
**Describe the bug**
PID Mode not set to "auto" by default, need to call the service to get PID working

**To Reproduce**
Just configure a new thermostat with basic configuration : 
```
  - platform: smart_thermostat
    name: Sejour
    unique_id: smart_thermostat_sejour
    heater: switch.virtual_radiateur_sejour
    target_sensor: sensor.atc_a1fd_temperature
    min_temp: 15
    max_temp: 22
    ac_mode: False
    target_temp: 19
    keep_alive:
      seconds: 60
    away_temp: 15
    sleep_temp: 18
    kp: 11
    kd: 0.01
    ki: 5
    pwm: 00:15:00 
``` 

**Expected behavior**
Expectation was that PID will be enabled by default and do PWM control of heater entity, but instead FULL ON till target +0.5 FULL OFF till target - 0.5

**Screenshots**
![image](https://github.com/user-attachments/assets/4a86156e-4ec0-471c-b43b-6493941694a9)

**Comment by jjmonteiro** [comment]
yeah this one got me as well.. banged my head for quite a while until I figured it out..

**Comment by maxeitelwein** [comment]
I do not understand how to call the service. Is it an action I have to configure or can in be found somewhere? It would be great, if you could help me with this! Thank you.

**Comment by 96Ems** [comment]
Simpliest method to activate PID Auto mode is to create a script and to run it every time HA is starting 

```
alias: PID MODE ON
sequence:
  - action: smart_thermostat.set_pid_mode
    metadata: {}
    data:
      mode: auto
    target:
      entity_id:
        - climate.bureau
        - climate.chambre
        - climate.sejour
        - climate.chambre_amis
description: ""
```

**Comment by ScratMan** [comment]
Your configuration is similar to mine, and I don't see such issue. Could you please enable debug logging for the integration in HA by adding the following to your configuration.yaml file:

```yaml
logger:
  logs:
    custom_components.smart_thermostat: debug
```

Then please reboot and share any line containing smart_thermostat.
