### ISSUE TITLE
Output higher than 100 (e.g. up to 255)

### ISSUE THREAD

**Issue by Xitee1** [ScratMan/HASmartThermostat#254]
**Is your feature request related to a problem? Please describe.**
My radiator valve can be controlled manually (Eurotronic Comet Zigbee) but the position does not use percent but a range between `0` and `255`.
Currently, the valve position is set to `100` instead of `255` when it should heat with 100% power.

**Describe the solution you'd like**
The ability to set `output_max` to higher values and allow the PID controller to use that range. Currently, when setting the max output value to `255`, it still won't go above `100`.

**Describe alternatives you've considered**
An automation and/or template number entity that translates percent to the absolute position of the valve and applies it to the radiator valve.

**Comment by Xitee1** [comment]
I managed to do this using a template number. It would still be nice to have that directly built in.

```yaml
template:
  - number:
      unique_id: my_unique_id
      name: "MyThermostat Valve position percent"
      state: >
        {% set value = int(states('number.mythermostat_valve_position')) %}
        {% set percentage = (value / 255) * 100 %}
        {{ int(percentage) }}
      set_value:
        - action: number.set_value
          data_template:
            value: >
              {% set percentage = value %}
              {% set calculated_value = (percentage / 100) * 255 %}
              {{ int(calculated_value) }}
          target:
            entity_id: number.mythermostat_valve_position
      unit_of_measurement: "%"
      step: 1
      min: 0
      max: 100
      optimistic: false
```
