### ISSUE TITLE
Valve not controllable by smart thermostat and warning about missing entities

### ISSUE THREAD

**Issue by maxeitelwein** [ScratMan/HASmartThermostat#259]
I am trying to set up the smart thermostat with a Shelly BLU TRV. I have successfully configured the Shelly BLU valve as an MQTT entity in my `configuration.yaml` as shown below:

```
mqtt:
  - valve:
      name: "Thermostat Ventil"
      unique_id: "8bb95425-a1ed-4309-9bb6-4faa962eeaac"
      command_topic: "homeassistant/shelly-blu-gw/rpc"
      command_template: '{{ {"id": 0,"src": "homeassistant","method": "BluTRV.Call","params": {"id": 200,"method": "TRV.SetPosition","params": {"id": 0,"pos": value}}} | to_json }}'
      reports_position: true
      state_topic: "homeassistant/shelly-blu-gw/status/trv-shelly-status/rpc"
      value_template: "{{ value_json.result['trv:0'].pos }}"
      optimistic: true
      availability:
        - topic: "homeassistant/shelly-blu-gw/online"
          payload_available: "true"
          payload_not_available: "false"
        - topic: "homeassistant/shelly-blu-gw/status"
          value_template: "{{ value_json.mqtt.connected }}"
          payload_available: "true"
          payload_not_available: "false"
```

The valve is correctly shown as an MQTT entity and responds as expected:

- The position can be controlled.
- The position is reported correctly.

However, when I attempt to use the smart thermostat component, I encounter the following warning message:
`[homeassistant.helpers.service] Referenced entities valve.thermostat_ventil are missing or not currently available`
Additionally, the thermostat entity shows as "Untätig" (idle/inactive), and I cannot control the valve position through the thermostat.

### Relevant Configuration

My smart thermostat config is as follows:

```climate:
  - platform: smart_thermostat
    name: Smart Thermostat
    unique_id: "87670575-1af7-4089-948f-cea8cdde2971"
    heater:
      - valve.thermostat_ventil
    target_sensor: sensor.shellyplusht_fcb4672659b0_temperature
    min_temp: 4
    max_temp: 30
    target_temp_step: 0.1
    target_temp: 25
    keep_alive:
      seconds: 60
    pwm: 0
    output_precision: 0
    kp: 5
    ki: 0.01
    kd: 500
    debug: true
```

I am running Home Assistant through Docker. I am on Core version 2024.10.3 and Frontend version 20241002.3. I have the latest smart_thermostat version.

### What Happens

- The valve state is not updating when the thermostat attempts to control it.
- The thermostat stays in "idle" mode, even when the target temperature is above the current temperature.
- If I manually set the valve state (e.g., from "open" to 0) using the Developer Tools, the thermostat switches to "heating" mode, but cannot set the valve to the requested position.

### What I've tried

- I’ve confirmed that the valve is functioning correctly when controlled manually (via MQTT or Homeassistant card).
- I’ve checked the debug output, and the position requested by the PID controller is correct.
- I’ve ensured that both the valve and thermostat entities are available, but the thermostat still shows the warning about the missing valve entity.

### Request for Help

I’m stuck and would appreciate any guidance on why the smart thermostat is unable to control the valve properly. Has anyone encountered a similar issue or can suggest what might be causing this problem?

**Comment by maxeitelwein** [comment]
**I got the thermostat to work, but not by using the valve entity. I had to resort to a light entity.** 

### Why the valve entity is not working

The thermostat was attempting to set the valve position using the `SERVICE_SET_VALUE` service from the probably deprecated `homeassistant.components.number.const` component. However, this service no longer exists, and it wasn't designed to handle valve position control, which expects `set_position` rather than `set_value`. Therefore, I used a light entity as a workaround.

### The constant idle problem

The idle problem occurs because the  `_is_device_active()` function in [climate.py](https://github.com/ScratMan/HASmartThermostat/blob/master/custom_components/smart_thermostat/climate.py#L926) was not correctly handling the valve state when `pwm = 0`. The state of the valve (or light) is represented as a string like `"on"`, `"off"`, `"open"` or `"closed"`, rather than a numerical value. As a result, the thermostat was unable to determine the device’s active state correctly. I fixed this by modifying the code to check if the state was `"on"`, which in my case indicated that the valve was in a position greater than 0.

I changed line 937 to:
```
return any([self.hass.states.get(heater_or_cooler_entity).state is "on" for heater_or_cooler_entity in self.heater_or_cooler_entity])
```
With this fix, the thermostat correctly detects when the valve is active, and it no longer stays in "idle" mode.

### My valve light config

```
mqtt:
  - light:
      name: "Thermostat Ventil"
      unique_id: "8bb95425-a1ed-4309-9bb6-4faa962eeaac"
      command_topic: "homeassistant/shelly-blu-gw/rpc"
      payload_off: '{"id": 0,"src": "homeassistant","method": "BluTRV.Call","params": {"id": 200,"method": "TRV.SetPosition","params": {"id": 0,"pos": 0}}}'
      enabled_by_default: true
      brightness_command_topic: "homeassistant/shelly-blu-gw/rpc"
      brightness_command_template: '{{ {"id": 0,"src": "homeassistant","method": "BluTRV.Call","params": {"id": 200,"method": "TRV.SetPosition","params": {"id": 0,"pos": value}}} | to_json }}'
      brightness_scale: 100
      brightness_state_topic: "homeassistant/shelly-blu-gw/status/trv-shelly-status/rpc"
      brightness_value_template: "{{ value_json.result['trv:0'].pos }}"
      on_command_type: "brightness"
      optimistic: true
      availability:
        - topic: "homeassistant/shelly-blu-gw/online"
          payload_available: "true"
          payload_not_available: "false"
        - topic: "homeassistant/shelly-blu-gw/status"
          value_template: "{{ value_json.mqtt.connected }}"
          payload_available: "true"
          payload_not_available: "false"
```
