### ISSUE TITLE
All smart_thermostats reports state = Unavailable 

### ISSUE THREAD

**Issue by tonkinbay** [ScratMan/HASmartThermostat#262]
All smart_thermostats reports state = Unavailable and reports this via card:

"This entity is no longer being provided by the smart_thermostat integration. If the entity is no longer in use, delete it in settings."

Both via 2025.6.0 and 2024.6.1

**Comment by tonkinbay** [comment]
Here is my config for three of my themostats:
```

  - platform: smart_thermostat
    name: Smart Thermostat PID Køkken
    unique_id: smart_thermostat_kokken
    heater: input_boolean.heater_kokken
    target_sensor: sensor.temperature_kokken
    target_temp: 20
    keep_alive:
      seconds: 60
    away_temp: 17
    kp: 5
    ki: 0.01
    kd: 500
    min_cycle_duration: 00:05:00
    min_off_cycle_duration: 00:05:00
  - platform: smart_thermostat
    name: Smart Thermostat PID Stue
    unique_id: smart_thermostat_stue
    heater: input_boolean.heater_stue
    target_sensor: sensor.temperature_stue
    target_temp: 20
    keep_alive:
      seconds: 60
    away_temp: 17
    kp: 5
    ki: 0.01
    kd: 500
    min_cycle_duration: 00:05:00
    min_off_cycle_duration: 00:05:00
  - platform: smart_thermostat
    name: Smart Thermostat PID TV Stue
    unique_id: smart_thermostat_tvstue
    heater: input_boolean.heater_tvstue
    target_sensor: sensor.temperature_tvstue
    target_temp: 20
    keep_alive:
      seconds: 60
    away_temp: 17
    kp: 5
    ki: 0.01
    kd: 500
    min_cycle_duration: 00:05:00
    min_off_cycle_duration: 00:05:00
```

**Comment by ScratMan** [comment]
What is the HA version?

**Comment by Ny-Mic** [comment]
I have the same issue. I'm using 
- Core 2024.11.3
- Supervisor 2024.11.4
- Operating System 13.2
- Frontend 20241106.2

**Comment by ScratMan** [comment]
Are the releases prior to 2024.6.0 working?
Is the  pre-release 2024.11.0-alpha1 working ?

**Comment by Ny-Mic** [comment]
Sorry, i can't answer this, because I installed Smart Thermonstat with 2024.11.3  and not earlier

**Comment by ScratMan** [comment]
Please add the following lines to your  HA configuration.yaml file, reboot, and provide related log entries mentioning `smart_thermostat`

```yaml
logger:
  default: warning
  logs:
    custom_components.smart_thermostat: debug

```
