### ISSUE TITLE
Alerting/Notification when thermostat has been "heating", yet the temperature has not increased (open-window, stuck actuator pin, etc)

### ISSUE THREAD

**Issue by vincedarley** [ScratMan/HASmartThermostat#285]
I would like to be able to create notifications based on a threshold to describe when the thermostat's heating efforts have not resulted in room temperature increases. This will allow me to take action (see if a window has been left open, see if the actuator pin on the heating valve is stuck, etc).

Ideally the thermostat would monitor how much heating it has requested over a configurable number of hours (underfloor heating is slow vs air heating), and compare that with the trajectory of the actual temperature. If the actual temperature trajectory is zero to negative, yet the heating-request is substantial over that time period, then there is presumably a problem of some kind.

Without having access to the internal state of the SmartThermostat, it is pretty impossible (I think) to build an automation to mimic this sort of outcome.

**Comment by ScratMan** [comment]
You can already use an automation to monitor the heating/idle state attribute, and send an alert if it's heating for too long.

```yaml
alias: Heating monitor
description: ""
triggers:
  - trigger: state
    entity_id:
      - climate.your_smart_thermostat_entity
    attribute: hvac_action
    to: heating
    for:
      hours: 0
      minutes: 50
      seconds: 0
conditions: []
actions:
  - action: notify.mobile_app_of_your_phone
    metadata: {}
    data:
      title: Heating alert !!
      message: There is an issue with the heater!
mode: single

```

And that would be much more flexible than integrating it in the smart thermostat component, allowing to enable another heater, check for some causes, depending on if the temperature is normal or not, or if there is someone to call at home first.
