### ISSUE TITLE
Climate turn on/off from automation not working

### ISSUE THREAD

**Issue by dominig** [ScratMan/HASmartThermostat#286]
**Describe the bug**
Changing the mode as  "Heat" or "off" does not work (anymore)

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a test automation
2. As Action select "Climate: Turn off"
3. Try to select an area -> nothing can be shown
4. If you had previously defined an area (as it used to work) it does nothing when action run

**Expected behavior**
Climate turn on and off should be possible to activate or deactivate the heating for a given zone

**Screenshots**

**Desktop (please complete the following information):**
 - OS: (VM on a Freebox)
    NAME="Alpine Linux"
    ID=alpine
    VERSION_ID=3.21.0
    PRETTY_NAME="Alpine Linux v3.21" 
    HOME_URL="https://alpinelinux.org/"
 
 - Smart thermostat Version 2021.11.1

**Additional context**
_** Action is defined as follow **_
alias: Window Bedroom Opened Stop heating
description: Set the heating to Away mode when window is opened
triggers:
  - type: opened
    device_id: a856b646ae1ff52860c226fe9ca67583
    entity_id: 535ce1b531950b68cbd583daa6a18303
    domain: binary_sensor
    trigger: device
conditions: []
actions:
  - data: {}
    target:
      area_id: chambre
    action: climate.turn_off
mode: single

**The configuration** is old an was created by hand. It used to work.
I see that note (is it relevant ?)
Integration entries
This integration was not setup via the UI, you have either set it up in YAML or it is a dependency set up by another integration. If you want to configure it, you will need to do so in your configuration.yaml file. 

_** my config file included **_
 - platform: smart_thermostat
    name: Smart Thermostat Bedroom
    unique_id: smart_thermostat_bedroom
    heater: switch.virtual_virtual_radiator_bedroom
    target_sensor: sensor.temperature_bedroom_temperature_2
    outdoor_sensor: sensor.larmor_plage_temperature
    min_temp: 7
    max_temp: 25
    ac_mode: False
    target_temp: 19
    away_temp: 5
    eco_temp: 17
    comfort_temp: 19
    target_temp_step: 0.1
    keep_alive: 00:05:00
    kp: 5.5
    ki: 0.0005
    kd: 300
    ke: 5
    pwm: 00:05:00
    min_cycle_duration: 00:01:00

**Comment by schmttc** [comment]
Hi, I had a similar issue that was caused by having the PWM value set when using a switch entity to control my heater.
If you enable debug logs, you may see the PID entity trying to set the switch to 100, when it requires an ON/OFF value.

I have raised PR #296 to update the documentation.

Example PWM issue logs:
```
2025-04-04 13:00:59.843 INFO (MainThread) [custom_components.smart_thermostat.climate] climate.oven_pid: Change state of switch.example_switch to 100.0
2025-04-04 13:00:59.843 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities switch.example_switch are missing or not currently available
```

Edit: Removing the PWM line in config fixed this issue for me initially, but after a subsequent reboot my PID controller still does not function
My config:
```
# Smart thermostat (PID)
climate:
  - platform: smart_thermostat
    name: Oven-PID
    unique_id: oven_pid
    heater: switch.smart_plug_switch
    target_sensor: sensor.oventemp_temperature
    min_temp: 0
    max_temp: 200
    ac_mode: False
    target_temp: 60
    keep_alive:
      seconds: 60
    away_temp: 14
    kp: 0.03217
    ki: 0.00008
    kd: 3.11207
```
