### ISSUE TITLE
Multiple heater entities

### ISSUE THREAD

**Issue by roko146** [ScratMan/HASmartThermostat#4]
Hello, very good integration to control. But I have a question. Is it possible to set more entities to heater property e.g.?

heater: 
    switch.on_off_relay_pin_1
    switch.on_off_relay_pin_2
    switch.on_off_relay_pin_3
    switch.on_off_relay_pin_4

**Comment by ScratMan** [comment]
Hello, my understanding of the code is that it does not support multiple heater entities.
If you need to control several relays with the thermostat output, you may use templates or scripts instead.

**Comment by jandado** [comment]
> Hello, very good integration to control. But I have a question. Is it possible to set more entities to heater property e.g.?
> 
> heater: switch.on_off_relay_pin_1 switch.on_off_relay_pin_2 switch.on_off_relay_pin_3 switch.on_off_relay_pin_4

Hi @roko146 , that is easy - configure a group in HA /config/groups.yaml like so:
```
on_off_relay_all_pins:
  name: "On Off Relay All Pins"
  entities:
    - switch.on_off_relay_pin_1
    - switch.on_off_relay_pin_2
    - switch.on_off_relay_pin_3
    - switch.on_off_relay_pin_4
```
Then use the switch.on_off_relay_all_pins as the heater.
