### ISSUE TITLE
Thermostat is constantly switching to Off - Comfort

### ISSUE THREAD

**Issue by sergimola** [ScratMan/HASmartThermostat#47]
Whatever mode I set every 30s or so, the thermostat is set to Off - Comfort and then back to "Idle - Home" (for instance) for some seconds.
Somehow it is actually working fine, it turns on and off the switch as expected and it works like a charm (kudos for this great thermostat!!) but in the UI the behaviour is quite strange.
In this screenshot you can see how the target temperature (in purple) is constantly changing from the current preset (sleep 16, home 19, etc.) to the Comfort setting (19.5).
![image](https://user-images.githubusercontent.com/16050368/145945155-311f4e8f-c8fb-4f5d-8b58-6d154808cbc9.png)

This is my config, what am I doing wrong?
```yaml
  - platform: smart_thermostat
    name: Heating
    heater: switch.heating
    target_sensor: sensor.living_room_temperature
    min_temp: 15
    max_temp: 22
    ac_mode: false
    target_temp: 18
    eco_temp: 18
    home_temp: 19
    comfort_temp: 19.5
    boost_temp: 21
    away_temp: 17
    sleep_temp: 16
    cold_tolerance: 0.2
    hot_tolerance: 0
    min_cycle_duration:
      minutes: 1
    keep_alive:
      seconds: 30
    initial_hvac_mode: "off"
    precision: 0.1
```

Thanks in advance!
