### ISSUE TITLE
climate.set_preset_mode forces preset mode to Away

### ISSUE THREAD

**Issue by ejalal** [ScratMan/HASmartThermostat#60]
**Describe the bug**
climate.set_preset_mode forces preset mode to Away of I call it with `preset_mode: "none"` since release 2021.12.5

**To Reproduce**
1. From HA Dev Tools
2. Call climate.set_preset_mode with preset mode
```
service: climate.set_preset_mode
data: 
  preset_mode: "none"
  entity_id: "all"
```
3. Thermostat is set to Away mode.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Reverted to 2021.12.4 and correct behavior was restored
